# -*- coding: utf-8 -*-
"""Trend Pendaftar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJX_BCkswIPu0gqKYjDykmwFb-XRZxYQ
"""

df.info()